name: superx
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dotted_border: ^3.1.0
  file_picker: ^10.3.3
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  firebase_database: ^12.0.2
  firebase_storage: ^13.0.2
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  image_picker: ^1.2.0
  intl: ^0.20.2
  percent_indicator: ^4.2.5
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  syncfusion_flutter_gauges: ^31.1.22

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/